---
#
# List of entities that is exposed to HomeKit/Siri
# From area: Things that don't belong in any specific area
#
# - alarm_control_panel.abode_alarm
# - input_boolean.person_arrives
# - input_boolean.last_person_leaves
