# alias: Side Door Unlock
# description: Unlock the side door when phones connect to wifi.

# id: 16620edc-2a4a-45b6-8a70-867947e69eac

# mode: single

# trigger:
#   - platform: state
#     entity_id: input_boolean.person_arrives
#     to: "on"
  
# action:
#   - alias: "Unlock side door"
#     service: lock.unlock
#     target:
#       entity_id: lock.side_door
#   - alias: "Reset helper"
#     service: input_boolean.turn_off
#     target:
#       entity_id: input_boolean.person_arrives    
      