alias: Side Door Unlock
description: Unlock the side door when phones connect to wifi.

id: 16620edc-2a4a-45b6-8a70-867947e69eac

mode: parallel

trigger:
  - platform: state
    entity_id:
      - person.ryan
      - person.nicole
      - person.angeline
    to: "home"
  
action:
  - alias: "Unlock side door"
    service: lock.unlock
    target:
      entity_id: lock.side_door    
      