# alias: Front Door Light On
# description: Turn on front porch light at dusk.

# id: 8d9ac402-3317-444c-8a25-087d982799aa

# mode: single

# trigger:
#   - platform: numeric_state
#     entity_id: sun.sun
#     attribute: elevation
#     below: 4
  
# action:
#   - alias: "Front door light on"
#     service: light.turn_on
#     target:
#       entity_id: light.front_door_light
