alias: Alarm Away
description: >-
  Arm the alarm when everyone leaves.

id: 8f0ae849-1e51-4976-ba1f-0fe09bdeaf4a

mode: queued

trigger:
  - platform: state
    entity_id:
      - person.ryan
      - person.nicole
      - person.angeline
    to: "away"

condition:
  condition: state
  entity_id:
    - person.ryan
    - person.nicole
    - person.angeline
  state: "away"
  
action:
  - alias: "Arm alarm"
    service: alarm_control_panel.alarm_arm_away
    target:
      entity_id: alarm_control_panel.abode_alarm