
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
automation split: !include_dir_list ./automations
script: !include scripts.yaml
scene: !include scenes.yaml

# Manual Configurations
homekit:
  name: HASS Bridge
  filter:
    include_entities: !include_dir_merge_list ./homekit

input_boolean:
  person_arrives:
    name: Person Arrives
  last_person_leaves:
    name: Last Person Leaves

# light:
#   - platform: group
#     name: Living Room Lights
#     entities:
#       - light.living_room_light_1
#       - light.living_room_light_2
#       - light.living_room_light_3
#       - light.living_room_light_4
#   - platform: group
#     name: Dining Room Lights
#     entities:
#       - light.dining_room_light_1
#       - light.dining_room_light_2
#       - light.dining_room_light_3
#   - platform: group
#     name: Office Lights
#     entities:
#       - light.office_ceiling_light
#       - light.office_lamp

