
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Manual Configurations
homekit:
  name: HASS Bridge
  filter:
    include_entities: !include_dir_merge_list ./homekit

input_boolean:
  backdoor_august_lock:
    name: Back Door August Lock
    icon: mdi:home-lock  
  side_door_august_lock:
    name: Side Door August Lock
    icon: mdi:home-lock
  front_door_august_lock:
    name: Front Door August Lock
    icon: mdi:home-lock
